import sys
import json


def generateJSON(jobs, profiles, platform_size, outputFileName):

    data = {
        "description": "Generated by swf2json script with command: {}".format(
            " ".join(sys.argv[:])
        ),
        "nb_res": platform_size,
        "jobs": jobs,
        "profiles": profiles,
    }

    try:
        outputJSONFile = open(outputFileName, "w")
        json.dump(data, outputJSONFile, indent=2)

        print(
            "Generated {} jobs with {} profiles to {}".format(
                len(jobs), len(profiles), outputFileName
            )
        )
    except IOError as ex:
        print(ex)


def generateJobData(uid_list, outputFileName):
    try:
        outputJSONFile = open(outputFileName, "w")
        json.dump(uid_list, outputJSONFile, indent=2)

        print("Export Uid list to {}".format(outputFileName))

    except IOError as ex:
        print(ex)